import React from "react";
import { BaseTemplateInterface } from "./BaseTemplateInterface";
import styles from "./BaseTemplate.module.css";
import Image from "next/image";
import Head from "next/head";
import Header from "../../components/header/Header";
import Sidebar from "../../components/sidebar/Sidebar";

const BaseTemplate: React.FC<BaseTemplateInterface> = ({ pageProp, children }) => {

  return (
  <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.base + " primary"}>
          <Sidebar />
          <div>
            content here
            <button className="button is-small">
            <span className="material-icons icon">
              add
            </span>
            </button>
          </div>
        </div>
      </main>
    </>
  )
}

export default BaseTemplate;